name: build
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "main"
jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Build
        run: dotnet build
      - name: Pack
        run: dotnet pack
      - name: Publish
        if: ${{ github.ref == 'refs/heads/master' && github.event_name != 'pull_request' }}
        run: |
          dotnet nuget add source --username ahwm --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/ahwm/index.json"
          dotnet nuget push "OpenSRS.NET\bin\Release\*.nupkg" --skip-duplicate --source "github" -k ${{ secrets.GH_NUGET }}
